# Generated by Django 3.2.3 on 2021-06-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_exam_app', '0003_rename_userss_car_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(related_name='friends', to='study_exam_app.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
