# Generated by Django 2.2.4 on 2021-05-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall_app', '0002_auto_20210528_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='messages',
            new_name='message',
        ),
    ]
